version: 2
project_name: opentelemetry-collector-releases
env:
  - COSIGN_YES=true
builds:
  - id: otelcol-contrib-linux
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64le
      - s390x
    goarm:
      - "7"
    dir: _build
    binary: otelcol-contrib
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
  - id: otelcol-contrib-darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    dir: _build
    binary: otelcol-contrib
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
  - id: otelcol-contrib-windows
    goos:
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
      - ppc64le
    dir: _build
    binary: otelcol-contrib
    ldflags:
      - -s
      - -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
checksum:
  name_template: '{{ .ProjectName }}_otelcol-contrib_checksums.txt'
monorepo:
  tag_prefix: v
partial:
  by: target
